site_name: SMSjet Documentation
theme:
  name: material
  features:
    - navigation.sections
  logo: https://f004.backblazeb2.com/file/smsjet/Subtractplane_light.png
  favicon: https://f004.backblazeb2.com/file/smsjet/Subtractplane_dark-2+copy.png
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - stylesheets/extra.css
nav:
  - Welcome to SMSjet Docs: index.md
  - User Guide:
      - user-guide/1. getting-started.md
      - user-guide/2. api.md
      - user-guide/3. phone-formatting.md
      - user-guide/4. 2FA Two Factor Authentication.md
      - user-guide/5. Contact Groups.md
      - user-guide/99. Supported-Countries.md
  - Integrations:
      - Integrations/1. Zapier.md
